### ISSUE TITLE
gperf 3.1

### ISSUE THREAD

**Issue by cromerc** [andywingo/elogind#8]
elogind fails to build on systems with gperf 3.1, here are the errors:

In file included from src/shared/errno-list.c:31:0:
src/shared/errno-from-name.h:143:1: error: conflicting types for ‘lookup_errno’
lookup_errno (register const char *str, register size_t len)
^~~~~~~~~~~~
src/shared/errno-list.c:27:33: note: previous declaration of ‘lookup_errno’ was here
static const struct errno_name* lookup_errno(register const char *str,
^~~~~~~~~~~~
make[2]: *** [Makefile:3142: src/shared/libelogind_shared_la-errno-list.lo] Error 1
make[1]: *** [Makefile:3865: all-recursive] Error 1

**Comment by kensington** [comment]
This is fixed upstream in systemd/systemd@c9f7b4d356a453a01aa77a6bb74ca7ef49732c08 and in elogind in elogind/elogind@dcb5dd132a821a15fbf767e296aa0ed97c0ebaef. It seems that a new release will not be too far away.

**Comment by Yamakuzure** [comment]
The new release is out at elogind/elogind, so this issue can be closed.
